/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as NamespacesRouteImport } from './routes/namespaces'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSplatRouteImport } from './routes/resources.$'

const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesRoute = NamespacesRouteImport.update({
  id: '/namespaces',
  path: '/namespaces',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSplatRoute = ResourcesSplatRouteImport.update({
  id: '/resources/$',
  path: '/resources/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/namespaces' | '/nodes' | '/resources/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/namespaces' | '/nodes' | '/resources/$'
  id: '__root__' | '/' | '/events' | '/namespaces' | '/nodes' | '/resources/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  NamespacesRoute: typeof NamespacesRoute
  NodesRoute: typeof NodesRoute
  ResourcesSplatRoute: typeof ResourcesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces': {
      id: '/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof NamespacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$': {
      id: '/resources/$'
      path: '/resources/$'
      fullPath: '/resources/$'
      preLoaderRoute: typeof ResourcesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  NamespacesRoute: NamespacesRoute,
  NodesRoute: NodesRoute,
  ResourcesSplatRoute: ResourcesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
