/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as NamespacesRouteImport } from './routes/namespaces'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContextsRouteImport } from './routes/contexts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSplatRouteImport } from './routes/resources.$'
import { Route as NodesNameRouteImport } from './routes/nodes_.$name'
import { Route as NamespacesNameRouteImport } from './routes/namespaces_.$name'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesRoute = NamespacesRouteImport.update({
  id: '/namespaces',
  path: '/namespaces',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsRoute = ContextsRouteImport.update({
  id: '/contexts',
  path: '/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSplatRoute = ResourcesSplatRouteImport.update({
  id: '/resources/$',
  path: '/resources/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNameRoute = NodesNameRouteImport.update({
  id: '/nodes_/$name',
  path: '/nodes/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesNameRoute = NamespacesNameRouteImport.update({
  id: '/namespaces_/$name',
  path: '/namespaces/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contexts': typeof ContextsRoute
  '/events': typeof EventsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/search': typeof SearchRoute
  '/namespaces/$name': typeof NamespacesNameRoute
  '/nodes/$name': typeof NodesNameRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contexts': typeof ContextsRoute
  '/events': typeof EventsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/search': typeof SearchRoute
  '/namespaces/$name': typeof NamespacesNameRoute
  '/nodes/$name': typeof NodesNameRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contexts': typeof ContextsRoute
  '/events': typeof EventsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/namespaces': typeof NamespacesRoute
  '/nodes': typeof NodesRoute
  '/search': typeof SearchRoute
  '/namespaces_/$name': typeof NamespacesNameRoute
  '/nodes_/$name': typeof NodesNameRoute
  '/resources/$': typeof ResourcesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contexts'
    | '/events'
    | '/logs'
    | '/metrics'
    | '/namespaces'
    | '/nodes'
    | '/search'
    | '/namespaces/$name'
    | '/nodes/$name'
    | '/resources/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contexts'
    | '/events'
    | '/logs'
    | '/metrics'
    | '/namespaces'
    | '/nodes'
    | '/search'
    | '/namespaces/$name'
    | '/nodes/$name'
    | '/resources/$'
  id:
    | '__root__'
    | '/'
    | '/contexts'
    | '/events'
    | '/logs'
    | '/metrics'
    | '/namespaces'
    | '/nodes'
    | '/search'
    | '/namespaces_/$name'
    | '/nodes_/$name'
    | '/resources/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextsRoute: typeof ContextsRoute
  EventsRoute: typeof EventsRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  NamespacesRoute: typeof NamespacesRoute
  NodesRoute: typeof NodesRoute
  SearchRoute: typeof SearchRoute
  NamespacesNameRoute: typeof NamespacesNameRoute
  NodesNameRoute: typeof NodesNameRoute
  ResourcesSplatRoute: typeof ResourcesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces': {
      id: '/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof NamespacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts': {
      id: '/contexts'
      path: '/contexts'
      fullPath: '/contexts'
      preLoaderRoute: typeof ContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$': {
      id: '/resources/$'
      path: '/resources/$'
      fullPath: '/resources/$'
      preLoaderRoute: typeof ResourcesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$name': {
      id: '/nodes_/$name'
      path: '/nodes/$name'
      fullPath: '/nodes/$name'
      preLoaderRoute: typeof NodesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces_/$name': {
      id: '/namespaces_/$name'
      path: '/namespaces/$name'
      fullPath: '/namespaces/$name'
      preLoaderRoute: typeof NamespacesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextsRoute: ContextsRoute,
  EventsRoute: EventsRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  NamespacesRoute: NamespacesRoute,
  NodesRoute: NodesRoute,
  SearchRoute: SearchRoute,
  NamespacesNameRoute: NamespacesNameRoute,
  NodesNameRoute: NodesNameRoute,
  ResourcesSplatRoute: ResourcesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
